package com.hlyp.api.bean;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Fri Jan 04 18:52:04 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated Fri Jan 04 18:52:04 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbggenerated Fri Jan 04 18:52:04 CST 2019
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.newtest
     *
     * @mbggenerated Fri Jan 04 18:52:04 CST 2019
     */
    private String newtest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.newtest2
     *
     * @mbggenerated Fri Jan 04 18:52:04 CST 2019
     */
    private String newtest2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Fri Jan 04 18:52:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Fri Jan 04 18:52:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated Fri Jan 04 18:52:04 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated Fri Jan 04 18:52:04 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbggenerated Fri Jan 04 18:52:04 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbggenerated Fri Jan 04 18:52:04 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.newtest
     *
     * @return the value of user.newtest
     *
     * @mbggenerated Fri Jan 04 18:52:04 CST 2019
     */
    public String getNewtest() {
        return newtest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.newtest
     *
     * @param newtest the value for user.newtest
     *
     * @mbggenerated Fri Jan 04 18:52:04 CST 2019
     */
    public void setNewtest(String newtest) {
        this.newtest = newtest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.newtest2
     *
     * @return the value of user.newtest2
     *
     * @mbggenerated Fri Jan 04 18:52:04 CST 2019
     */
    public String getNewtest2() {
        return newtest2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.newtest2
     *
     * @param newtest2 the value for user.newtest2
     *
     * @mbggenerated Fri Jan 04 18:52:04 CST 2019
     */
    public void setNewtest2(String newtest2) {
        this.newtest2 = newtest2;
    }
}